---
name: player-info
version: 0.0.1
main: phrqndy\playerinfo\Main
api: 5.25.2
src-namespace-prefix: phrqndy\playerinfo

commands:
  info:
    description: Get information about a player
    usage: "/info {player}"
    permission: playerinfo.command

permissions:
  playerinfo.command:
    description: "Allows users to view player information"
    default: op
...
